baseURL: https://docs.sourcebots.co.uk
languageCode: en-gb
title: SourceBots Documentation
theme: learn

params:
    author: SourceBots
    description: SourceBots Documentation
    showVisitedLinks: false
    disableInlineCopyToClipBoard: true
    disableLanguageSwitchingButton: true
    disableAssetsBusting: true
    ordersectionsby: "weight"
    editURL: "https://github.com/sourcebots/docs/tree/master/content/"

    pythonVersion: 3.5.3

menu:
    shortcuts:
        - name: "<i class='fa fa-github'></i> Github Repo"
          url: https://github.com/sourcebots/docs

        - name: "<i class='fa fa-globe'></i> Website"
          url: https://sourcebots.co.uk/

enableGitInfo: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
enableEmoji: true
taxonomies: []
pygmentsCodeFencesGuessSyntax: true
disableKinds:
    - taxonomy
    - taxonomyTerm

outputs:
  home:
    - html
    - json

buildFuture: true
