[build]
    publish = "public/"
    command = "./scripts/build.sh"

[context.production.environment]
    HUGO_VERSION = "0.40"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.40"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.40"
